version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
  db:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
  pgadmin:
